/***************************************************
* @Copyright(c) 2016-2100.  hwl.  All rights reserved.
* @FileName: DMX512_API.h
* @Author:   hwl 
* @Description:  DMX512 Application header file
* @Version:
* @History:         
      <author>  <time>      <version >   <desc>
				hwl      18/9/7       1.0     
****************************************************/


#ifndef _ST7567_API_H_
#define _ST7567_API_H_



void ui_display_init(void);
void ui_display(void);
void ui_display_start(void);
#endif
